---
- name: Install PgBouncer
  ansible.builtin.apt:
    name: percona-pgbouncer
    state: latest

- name: Create PgBouncer directories
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "/var/log/pgbouncer/", mode: "2755", owner: postgres, group: adm }

- name: Copy PgBouncer configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "pgbouncer.logrotate", dest: "/etc/logrotate.d/pgbouncer", owner: "root", group: "root", mode: "0644" }

- name: Set up PgBouncer authentication
  include_tasks: pgbouncer_auth.yml

- name: Copy PgBouncer config
  ansible.builtin.template:
    src: pgbouncer.j2
    dest: /etc/pgbouncer/pgbouncer.ini
    owner: postgres
    group: postgres
    mode: "0644"
    backup: yes
  notify: "reload pgbouncer"

- name: Generate PgBouncer userlist.txt from variables
  ansible.builtin.template:
    src: userlist.j2
    dest: /etc/pgbouncer/userlist.txt
    owner: postgres
    group: postgres
    mode: "0640"
  notify: "reload pgbouncer"

- name: Enable and start PgBouncer service
  ansible.builtin.systemd:
    name: pgbouncer
    enabled: yes
    state: started
    daemon_reload: yes

- name: Clean up default Ubuntu PgBouncer log file
  ansible.builtin.file:
    path: /var/log/postgresql/pgbouncer.log
    state: absent
