---
- name: Check if PSQL passwords are defined
  ansible.builtin.fail:
    msg: "Error: PSQL superuser or replication passwords are not defined!"
  when: >
    psql_superuser_password | default('') | length == 0 or
    psql_replication_password | default('') | length == 0
  no_log: true

- name: Stop and Disable default PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Install dependencies for Patroni logging and etcd
  ansible.builtin.apt:
    name:
      - patroni
      - python3-pythonjsonlogger
      - python3-etcd
      - python3-requests
      - python3-yaml
      - python3-psycopg2
      - python3-six
    state: present
    update_cache: yes

- name: Create Patroni and PostgreSQL directories
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: /etc/patroni/, mode: "0755", owner: root, group: root }
    - { path: /var/log/patroni/, mode: "2755", owner: postgres, group: adm }
    - { path: /var/log/postgresql/, mode: "2755", owner: postgres, group: adm }
    - { path: "{{ psql_wal_dir }}", mode: "0700", owner: postgres, group: postgres }
    - { path: "{{ psql_data_dir }}", mode: "0700", owner: postgres, group: postgres }

- name: Copy PostgreSQL configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "postgresql.logrotate", dest: "/etc/logrotate.d/postgresql", owner: "root", group: "root", mode: "0644" }

- name: Create or update Patroni config
  ansible.builtin.template:
    src: patroni.j2
    dest: /etc/patroni/config.yml
    backup: yes
  notify: "restart patroni"

- name: Enable and start Patroni service
  ansible.builtin.systemd:
    name: patroni
    enabled: yes
    state: started
    daemon_reload: yes
