---
- name: "Install necessary packages for PostgreSQL and disk management"
  apt:
    name:
      - xfsprogs
      - parted
      - acl
      - curl
      - jq
      - vim
    state: present
    update_cache: true

- name: "Create partition on additional disk for PostgreSQL (/dev/sdb)"
  parted:
    device: /dev/sdb
    number: 1
    state: present
    fs_type: xfs

- name: "Format partition to XFS filesystem"
  filesystem:
    fstype: xfs
    dev: /dev/sdb1

- name: "Create directory for PostgreSQL data"
  file:
    path: /var/lib/postgresql
    state: directory
    mode: "0755"

- name: "Mount disk and update /etc/fstab"
  mount:
    path: /var/lib/postgresql
    src: /dev/sdb1
    fstype: xfs
    opts: defaults,noatime
    state: mounted
