---
# Common configuration
postgres_hosts: []
pgbackrest_repo_type: "posix" # Options: "posix", "azure"
pgbackrest_stanza: "test-stanza"
pgbackrest_cipher_pass: 'cipher pass'
psql_data_dir: "/var/lib/postgresql/data"

# For POSIX storage configuration
pgbackrest_repo_host: "pgbackrest-repo-host"
pgbackrest_repo_path: "/var/lib/pgbackrest"

# For Azure storage configuration
pgbackrest_azure_account: "testaccount"
pgbackrest_azure_key: "testkey"
pgbackrest_azure_key_type: "auto" # Options: "auto", "shared", "sas"
pgbackrest_azure_container: "testcontainer"

# Backup schedule (cron format fields)
pgbackrest_backup_full_cron:
  minute: "0"
  hour: "2"
  day: "*"
  month: "*"
  weekday: "0"

pgbackrest_backup_diff_cron:
  minute: "0"
  hour: "2"
  day: "*"
  month: "*"
  weekday: "1-6"
