---
- name: Create schemas for each database if defined
  community.postgresql.postgresql_schema:
    name: "{{ schema_item.name }}"
    db: "{{ db_spec.name }}"
    owner: "{{ schema_item.owner | default(db_spec.owner) }}"
    comment: "{{ schema_item.comment | default(omit) }}"
    state: present
    login_unix_socket: "/var/run/postgresql"
  become_user: postgres
  loop: "{{ databases | subelements('schemas', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.name }} -> {{ item.1.name }}"
  vars:
    db_spec: "{{ item.0 }}"
    schema_item: "{{ item.1 }}"
  when: is_primary | default(false)
