---
- name: "Prepare PostgreSQL Cluster Nodes"
  hosts: "db_cluster"
  become: true
  tags: ["preparation"]
  tasks:
    - name: "Run Percona setup"
      include_role:
        name: "percona_repo"
      tags: ["percona_repo"]

    - name: "Run LVM setup"
      include_role:
        name: "lvm"
      when: lvm_state is defined
      tags: ["lvm"]

- name: "Configure pgBackRest Repository"
  hosts: "db_cluster"
  become: true
  tags: ["backup"]
  roles:
    - { role: "pgbackrest", tags: ["pgbackrest"] }

- name: "Create PostgreSQL Cluster"
  hosts: "pg_nodes"
  become: true
  tags: ["cluster"]
  roles:
    - { role: "etcd", tags: ["etcd"] }
    - { role: "postgresql", tags: ["postgresql"] }
    - { role: "patroni", tags: ["patroni"] }
    - { role: "pgbouncer", tags: ["pgbouncer"] }
