---
- name: "Create PostgreSQL Cluster"
  hosts: db_cluster
  become: yes
  roles:
    - { role: "etcd", tags: ["etcd"] }
    - { role: "percona_postgresql", tags: ["postgresql"] }
    - { role: "patroni", tags: ["patroni"] }
    - { role: "pgbouncer", tags: ["pgbouncer"] }
    - { role: "pgbackrest", tags: ["pgbackrest"] }
