# Hosts
postgres_hosts: "{{ groups['pg_nodes'] }}"

# PostgreSQL configuration
psql_version: "18"
psql_data_dir: "/var/lib/postgresql/data"

# pgBackRest configuration
pgbackrest_stanza: "ppg-cluster"
pgbackrest_repo_type: "posix"
pgbackrest_repo_path: "/mnt/pgbackrest/ppg-cluster"
pgbackrest_repo_host: "dev-gis-s3"
