---
- name: "Install pgBackRest"
  ansible.builtin.package:
    name: percona-pgbackrest
    state: present

- name: "Remove default pgbackrest config if exists"
  ansible.builtin.file:
    path: "/etc/pgbackrest.conf"
    state: "absent"
