---
- name: "Install pgBackRest"
  include_tasks: install.yml

- name: "Create pgBackRest user and configure SSH access"
  include_tasks: user.yml

- name: "Configure pgBackRest"
  include_tasks: config.yml

- name: "Setup pgBackRest backup cron jobs"
  include_tasks: cron.yml
