---
- name: "Create .ssh directory for postgres user"
  ansible.builtin.file:
    path: "{{ psql_home_dir }}/.ssh"
    state: directory
    owner: "postgres"
    group: "postgres"
    mode: "0700"

- name: "Create backup directory"
  ansible.builtin.file:
    path: "{{ pgbackrest_repo_path }}"
    state: directory
    owner: "postgres"
    group: "postgres"
    mode: "0750"
