# Ansible variables
ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q oleksandrix@{{ hostvars[groups["jumpbox"][0]]["ansible_host"] }}"'

# LVM configuration for PostgreSQL data storage
lvm_state: "create"
pv_devices: ["/dev/sdb"]
vg_name: "vg_pgdata"
lv_name: "lv_pgdata"
fs_type: "xfs"
mount_path: "/var/lib/postgresql"

# General configuration
postgres_monitoring_user: "exporter"

# Hosts
etcd_hosts: "{{ groups['db_cluster'] }}"
postgres_hosts: "{{ groups['db_cluster'] }}"
allow_connection_hosts: []

# etcd configuration
etcd_version: "v3.6.9"
etcd_cluster_token: "ppg-cluster-dev-token"
etcd_data_dir: "/var/lib/etcd/postgresql"

# PostgreSQL configuration
psql_version: "17"
psql_home_dir: "/var/lib/postgresql"
psql_data_dir: "/var/lib/postgresql/data"
psql_bin_dir: "/usr/lib/postgresql/{{ psql_version }}/bin"

# Patroni configuration
patroni_scope: "postgresql-cluster"
patroni_namespace: "/service/"

# pgBackRest configuration
pgbackrest_user: "pgbackrest"
pgbackrest_repo_type: "azure"
pgbackrest_stanza: "ppg-cluster"
pgbackrest_azure_account: "ppgclusterpgbackrest"
pgbackrest_azure_container: "pgbackrest-repo"
