---
- name: "Install Percona PostgreSQL"
  ansible.builtin.apt:
    name:
      - "percona-postgresql-{{ psql_version }}"
      - "percona-postgresql-server-dev-{{ psql_version }}"
    state: present
    update_cache: yes

- name: "Stop and disable default PostgreSQL service"
  ansible.builtin.systemd:
    name: "postgresql"
    state: stopped
    enabled: no
  ignore_errors: yes

- name: "Clean up PostgreSQL log file"
  ansible.builtin.file:
    path: "/var/log/postgresql/postgresql-{{ psql_version }}-main.log"
    state: absent
