plugin: azure.azcollection.azure_rm
auth_source: cli
plain_host_names: true

include_vm_resource_groups:
  - rg-ppg-cluster-dev

keyed_groups:
  - prefix: ""
    separator: ""
    key: tags.AnsibleGroup
