# PostgreSQL extensions configuration
extension_map:
  postgis:
    packages:
      - "percona-postgresql-{{ psql_version }}-postgis-3"
  timescaledb:
    packages:
      - "timescaledb-2-postgresql-{{ psql_version }}"
    repo:
      name: "timescaledb"
      script: "curl -s https://packagecloud.io/install/repositories/timescale/timescaledb/script.deb.sh | sudo bash"
  pg_cron:
    packages:
      - "postgresql-{{ psql_version }}-cron"
  redis_fdw:
    install_script: |
      apt install -y libhiredis-dev percona-postgresql-server-dev-{{ psql_version }} clang-18 git
      cd /tmp
      git clone https://github.com/pg-redis-fdw/redis_fdw.git -b REL_{{ psql_version }}_STABLE
      cd redis_fdw
      make USE_PGXS=1
      sudo make install USE_PGXS=1
