---
- name: "Check if pgBackRest stanza already exists"
  ansible.builtin.command:
    cmd: "pgbackrest --stanza={{ pgbackrest_stanza }} info"
  become_user: "postgres"
  register: pgbackrest_stanza_check
  changed_when: false
  failed_when: false
  run_once: true

- name: "Create pgBackRest stanza"
  ansible.builtin.command:
    cmd: "pgbackrest --stanza={{ pgbackrest_stanza }} stanza-create"
  become_user: "postgres"
  register: pgbackrest_stanza_create
  retries: 10
  delay: 15
  until: pgbackrest_stanza_create.rc == 0
  run_once: true
  when: "pgbackrest_stanza_check.rc != 0 or ('status: error' in (pgbackrest_stanza_check.stdout | lower))"
