---
- name: "Common setup for PostgreSQL cluster nodes"
  hosts: "db_cluster"
  become: true
  vars:
    lvm_state: "extend"
    pv_devices: ["/dev/sdb", "/dev/sdc"]
    vg_name: "vg_pgdata"
    lv_name: "lv_pgdata"
    fs_type: "xfs"
    mount_path: "/var/lib/postgresql"
  roles:
    - { role: "lvm" }
